### PR TITLE
use 'cloudml' prefix for command line arguments we own

### PR DESCRIPTION
**Pull request by kevinushey**
This PR standardizes the names of the command line arguments we pass a little bit, and uses the `parse_arguments()` API to read + handle them.

### CODE REVIEW

**Comment by jjallaire** [comment]
Assuming this is for the purpose of distinguishing other parameters passed to us by the hyperparameter tuning engine?

If you haven't done so already if you could test to make sure `predict_local` and `predict_cloudml` both still work successfully before merging that would be great (making sure we avoid 11th hour breakage!).

**Comment by kevinushey** [comment]
That's indeed the intended purpose (+ this makes things cleaner as well, IMHO). I'll double-check that this doesn't regress anything and merge if it looks fine.

**Comment by kevinushey** [comment]
I had to make some amendments to the `deploy.R` script to get this working; I think we should save this PR until after the demo given the number of changes required just to be safe.

**Comment by jjallaire** [comment]
Okay sounds good!

**Pull request merged**
