### PR TITLE
Caching, packrat and travis improvements

### PR DESCRIPTION
**Pull request by javierluraschi**
There is already support for caching r packages, but similar improvements could be used to lower training time while using keras datasets and python packages. Completed work:

- Support for caching pip packages, currently disabled **[reverted]**
- Support to cache packrat appropriately and example.
- Support to cache keras data dir.
- Support to test multiple config files in travis.
- Support disabling keras installation and upgrading r to allow fast startup times.

The big improvement in performance is the work to enable packrat for keras while maintaining descent execution times:

screen shot 2017-12-08 at 4 31 19 pm

screen shot 2017-12-08 at 4 28 19 pm

Python package caching was reverted since it showed a performance degradation rather than an improvement. This is, most likely, explained by further optimizations in cloudml to which invalidating the state of the `sitepackages()` triggers further work that offsets the improvements of caching.

### CODE REVIEW

**Comment by jjallaire** [comment]
I've been attempting to get `cloudml_train` to work with a keras script and get this error:

screen shot 2017-12-04 at 6 00 32 pm

Are we currently installing keras and have you gotten a keras script to train yet?

**Comment by javierluraschi** [comment]
@jjallaire I hit that error when [setup.py#L41-L45](https://github.com/rstudio/cloudml/blob/master/inst/cloudml/setup.py#L41-L45) was not properly configured, but my guess is that you are synced to the latest commit.


The way I'm running the keras example is as follows:

```
setwd("inst/examples/keras")
```

Manually modify the `cloudml.yml` file to:

```
gcloud:
  project         : "rstudio-cloudml"
  account         : "javier@rstudio.com"
  region          : "us-east1"

cloudml:
  storage         : "gs://rstudio-cloudml/keras"
```

Run `job <- cloudml_train()`, mind trying out with latest and this example to scope this issue a bit?

Here are some successful runs from travis...

screen shot 2017-12-04 at 10 15 09 pm

I wonder if we are hitting more environment inconsistencies that we hit intermittently.

**Comment by jjallaire** [comment]
Just ran my example again and success! 

Could it be there is something that happens on the very first run of a project? I'll try a new project again to see what happens.

**Comment by jjallaire** [comment]
Created a brand new project and it ran successfully the first time. I think we are good to go!

**Comment by javierluraschi** [comment]
K, good to know. I'll keep an eye in case we hit this again to investigate further.

**Comment by javierluraschi** [comment]
Here are some perf numbers with MNIST for posterity...

1. Setting `latestr: False` and `keras: False`, `us-central1` used to be faster, we got `1:30` there, but it takes too long to get a machine most times:

screen shot 2017-12-06 at 12 18 49 am

2. Setting `latestr: True` and `keras: True` which install keras and dependencies with `pip isntall` adds `1:00`:

screen shot 2017-12-06 at 12 19 41 am

3. Using an additional `pip install` dir (somehow) adds `1:00`, and `0:30` for upload time:

screen shot 2017-12-06 at 1 54 43 am

4. Restoring `pip install` from remote dir (somehow) adds `1:00`:

screen shot 2017-12-06 at 12 28 41 am

Therefore, something needs to be optimized or further investigated...

**Pull request merged**
